apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: envoy-gateway
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.9.1

      helm:
        valueFiles:
          - $values/platform/envoy-gateway/values.yaml

    - repoURL: https://github.com/katerrado/kubernetes-production-lab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
