apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-smoke-test
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/katerrado/kubernetes-production-lab.git
    targetRevision: main
    path: platform/smoke-test

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
