apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routes
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/katerrado/kubernetes-production-lab.git
    targetRevision: main
    path: platform/routes

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
