grafana:
  enabled: true

  sidecar:
    datasources:
      enabled: true
      skipReload: true
      initDatasources: true

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.logging.svc.cluster.local
      isDefault: false
      editable: true
      jsonData:
        maxLines: 1000

  deploymentStrategy:
    type: Recreate

  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
